### ISSUE TITLE
Some more tweaks

### ISSUE THREAD

**Issue by DevTimur** [MoonManModding/EmergingTechnology#13]
There are two tweak i think VERY needed for better usability

1) JEI support for Shredder and Processor (Because everyone uses JEI nowadays)
2) Grow bed should show combined percent of bed with Media and Light with Bulb.
Like so
![image](https://user-images.githubusercontent.com/22171136/70884491-d7168700-1fde-11ea-87a0-300dc9c977b2.png)
or so
![image](https://user-images.githubusercontent.com/22171136/70884534-e72e6680-1fde-11ea-8b16-3c880e50dbe4.png)
That would make it much more obvious.

And btw, why don't you call your plastic a Bioplastic? It's obviously ECO-friendly, because made of sugarcanes.
https://en.wikipedia.org/wiki/Bioplastic

Actually, doesn't really matter what materials you use for your machines. Most of modpack developers will alter your recipes anyways. Most important in your mod is it's functionality. And so far it looking good. Not great, but good.

If you want to make it great, you better add some "Depth" to your mod. 
You see, there are already couple famous mods adding own ways to grow plants.
1) Immersive Engineering - Garden Cloche (easy, automated and just OP)
2) Thermal Expansion - Phytogenic Insolator (not so easy but automated)
3) Actually Additions - Greenhouse Glass (cheap and easy to use, no automation)
4) Mystical Agriculture - Growth Accelerator (cheap and easy to use, no automation)
5) Calculator - Flawless Greenhouse (VERY fast and automated)
6) Agricraft - the whole mod is for growing plants. No automation.

But every mod got kinda own way to grow plant. So and your mod require own "Quirk".
Your mod is kinda "High-tech" and "Futuristic", unlike all others, so add more techy things to it. Like...
1) Auto-harvesting and auto-planting robot
![image](https://user-images.githubusercontent.com/22171136/70885753-6cffe100-1fe2-11ea-9a7e-6551cc0ca6c8.png)
2) Nutrient additions (Bonemeal, Niter, or idk.) https://en.wikipedia.org/wiki/Fertilizer
![image](https://user-images.githubusercontent.com/22171136/70886105-5e65f980-1fe3-11ea-931f-b1bc89d77874.png)
3) Carbon dioxide. 
![image](https://user-images.githubusercontent.com/22171136/70886320-e21fe600-1fe3-11ea-9256-114ba3ded2ac.png)
And what ever else can increase yeld and growth speed of Hydroponics.
The more reasonable complexity you add for better yeld, the more interesting your mod becomes.

**Comment by MoonManModding** [comment]
This is _awesome_.

Love those sketches - are they yours?

In answer to your questions:

> JEI support for Shredder and Processor

I'll try to get this in the next version. Wanted to get the GUI usable first.

> Grow bed should show combined percent of bed with Media and Light with Bulb.

Wasn't sure whether having the light boost would get confusing if it was in both the light and bed GUI, but I agree it would be nice to see all boosts in one screen.

> And btw, why don't you call your plastic a Bioplastic? It's obviously ECO-friendly, because made of sugarcanes.

I am planning to split the plastics out into different types, e.g. strong, bio, transparent etc with different properties and uses depending on the resource used to create them.

> And so far it looking good. Not great, but good.

Welp it's only my first mod, two weeks in. It's getting there 😉

> You see, there are already couple famous mods adding own ways to grow plants.

I am definitely not trying to compete with these mods at this stage. The hydroponics part of this mod is only one element among others, and like I've said before, I didn't intend for this to be **the** hydroponics mod as I'm just one guy working on it part time 😋. 

Having said that, I seriously love those ideas for automation, nutrient fluids and CO2 sprayers (the sketches are inspired). I think 2 & 3 will be straighforward to implement, but automation seems a bit daunting at this stage. If you have any suggestions on how you think automation would/should work from your experience of other mods, let me know and I'll see what I can do.

Thanks again for taking the time to test the mod and give great feedback 👍

**Comment by MoonManModding** [comment]
Closing as many of these suggestions have been implemented. Thanks!
