### ISSUE TITLE
[SUGGESTION] some ideas

### ISSUE THREAD

**Issue by EnnekPL** [MoonManModding/EmergingTechnology#14]
HI!
I have some ideas  maybe you will like.
1. Makeing nutrient solution for hydroponics. mixer block (input - fertilizer or Chemicals, output - liquid water with nutrient solution). mixed water go to beds
2. If possibile AQUAPONICS :D You can add Fish tank (multi block), pump and pipes, and some food for fish [https://originhydroponics.com/online-training-for-aquaponics/](url)
3. Your owne plants thats growing is depend on the days (like harvest festival mod)
fe. tomato grow 20 minecraft days, when using bulbs numbers of days decrease, this system give you ability to add more option/mecanics to decrease growing days
4. blocks to build nice greenhouse

**Comment by MoonManModding** [comment]
Hello! Thank you for your suggestions 😁

1. I'm looking into this but haven't decided the best way to do it yet. I don't really want to add a bunch of new fluids for each input type but we'll see.

2. Once the mod is ported to 1.14 in the future, I'll use the fish from that update to do aquaponics 🐟

3. I currently have no plans to add my own crops as there are thousands from other mods. This may change in the future, however.

4. I will be adding more decorative blocks eventually to make more interesting structures, including plastic-based glass and others.

Thanks again!
