### ISSUE TITLE
[Suggestion] New mod idea maybe?

### ISSUE THREAD

**Issue by DevTimur** [MoonManModding/EmergingTechnology#15]
Not saying this is very necessary but maybe you consider making new, small mod.
This mod should do a simple thing, get list of mobs ID's from config file, and apply atribute so mobs don't suffocate in Galacticraft no-air space.
Here is API for mobs.
[LINK](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/api/entity/IEntityBreathable.java)

Not sure if this helps, but here is a mod that takes vanila mobs and add new AI to them
[LINK](https://github.com/Flemmli97/ImprovedMobs/tree/master/src/main/java/com/flemmli97/improvedmobs)
Maybe you can figgure out how to inject this atribute

Here is example of atribute implementation
[LINK](https://github.com/micdoodle8/Galacticraft/blob/33af6a3803b6ccc7c5030da13bcfda6c1cec4750/src/main/java/micdoodle8/mods/galacticraft/core/entities/EntityEvolvedWitch.java)
You add:
_import micdoodle8.mods.galacticraft.api.entity.IEntityBreathable;_
and
_public class EntityEvolvedWitch extends EntityWitch implements IEntityBreathable_
And the rest... unfortunately i don't know how to make this mod, maybe you can figure it out.

Ofcourse this mod will be yours, no need to mention me. All i need is mod for my modpack.

But if you have no time for this, no problem. I just wanted to add some non-Galacticraft mobs on a moon. Exept they suffocate and die.
And not only me mentioned this request [LINK](https://forum.micdoodle8.com/index.php?threads/mob-oxygen-option.5015/#post-36670) but left un-answered.
Thanks!

**Comment by MoonManModding** [comment]
Hi,

I'd have to do a bit of investigation into this, but if it's a lot of work I may not have the time. Is it just vanilla mobs you want to breathe in Galacticraft?

**Comment by DevTimur** [comment]
Quite the opposite. I want to tweak modded mobs. But by your question I start to suspect there is a problem with injecting into mobs from different mods. I don't know how mods work. So I think you shouldn't even bother. Maybe contacting with mod authors would be better thing to do. Just some of them long time inactive.

**Comment by MoonManModding** [comment]
Well in that case probably the simplest thing to do is clone the Galacticraft repository and just change their IBreathable interface a bit. You could then have your own custom Galacticraft mod, although that would mean you would have to update it if you wanted a new version of Galacticraft (not a problem if you don't update Galacticraft often).

Without having looked to deeply into it, I think the alternative is compiling your modded mobs mod against Galacticraft and have them implement the IBreathable interface.

I'll take a look tonight and let you know if it's straightforward 👍

**Comment by MoonManModding** [comment]
So it looks like the latter option might be best. You'd need to basically make your other mob-mods into an addon for Galacticraft and have them implement IBreathable (which may be a pain if you have quite a few mods).

It's likely there is an easier/hackier way to do this, but unfortunately I'm not good enough at modding yet to do it. I'd recommend joining one of the many modding Discord channels and asking them - lots of people [here](https://discordapp.com/invite/moddedmc) enjoy a challenge 😎
