### ISSUE TITLE
1.2.8-beta Crashes

### ISSUE THREAD

**Issue by Vatarus** [MoonManModding/EmergingTechnology#16]
Since version 1.2.7-beta the game crashes (including 1.2.8-beta)

========================================
[crash-2019-12-29_13.34.40-client.txt](https://github.com/MoonManModding/EmergingTechnology/files/4007728/crash-2019-12-29_13.34.40-client.txt)

**Comment by MoonManModding** [comment]
Thanks for reporting this! 👍 Should be fixed as of [version 1.2.9](https://www.curseforge.com/minecraft/mc-mods/emerging-technology-hydroponics/files/2851232)

**Comment by Vatarus** [comment]
Good job. Good mod.
Thanks. Everything is working now.
