### ISSUE TITLE
Agricraft doesn't seem working properly with Grow Lights

### ISSUE THREAD

**Issue by genom10** [MoonManModding/EmergingTechnology#18]
![image](https://user-images.githubusercontent.com/50977138/71668663-6a500a80-2d9c-11ea-9180-b78c0801f537.png)
Plants on Argicraft Crops must have an empty block on top of them to grow. But Grow Lights don't apply their bonuses if placed higher.

**Comment by MoonManModding** [comment]
Not sure if this will fix it, but if you check the configuration for Emerging Technology there should be an option to change light range (hydroponics module > grow lights > Grow Light - Range).

Would you mind changing that to something like 4-5 and letting me know if that resolves the issue?

**Comment by genom10** [comment]
It works! In some unobvious and unsatisfying way but it works!
![image](https://user-images.githubusercontent.com/50977138/71680543-f4a86680-2dbc-11ea-9e80-d113a50b7448.png)

**Comment by MoonManModding** [comment]
Hahaha, phew! I think if you look in the GUI of the lights/grow bed it should tell you what the growth boost is from the lights too ([example from CurseForge](https://media.forgecdn.net/attachments/272/902/gui-example.png))

**Comment by genom10** [comment]
It does! For some reason I've had max range of lamps set to 1. Thanks for help. But it still quite unsatisfying to have visibly unnecessary space between lamp and crops :\
