### ISSUE TITLE
Discussion - Growth Media

### ISSUE THREAD

**Issue by MoonManModding** [MoonManModding/EmergingTechnology#2]
Please post any suggestions and ideas related to [Growth Media](https://en.wikipedia.org/wiki/Hydroponics#Substrates_(growing_support_materials)) here

**Comment by genom10** [comment]
What about an option to replace water with other liquids with different grow modifiers. Like mineralized/fertilized water for faster growth or lava for growing nether warts.

**Comment by MoonManModding** [comment]
I've been looking into this but haven't settled on anything yet. I don't really want to add custom liquids to the mod at this point as it may overcomplicate things, but it would be cool to use liquids from other mods. If you can think of any that would work let me know.
