### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by PlatinumFox** [MoonManModding/EmergingTechnology#21]
Hello, first off i just want to say i LOVE the mod so far. 

Automation has been difficult for me (I could just be a complete idiot though)
 the wiki states that placing the shredder over the processor should auto output those items into the processor. this does not work for me. 
i have also tried using pipes from various mods to remove items from the shredder, processor and the harvester and i have had no such luck. Mods Pipes i used are Buildcraft, Applied energistics 2, thermal series.

the vanilla hopper does not work on the shredder or processor either, it does work on the harvester however.

also when there is the shredder and processor are stacked the items are deleted. 

TL;DR: We need Plumber

**Comment by MoonManModding** [comment]
Hello! Thank you for reporting this 😊 

Unfortunately the output process for the shredder wasn't written to handle the new plastic items I added, but I will do my best to improve it in the next release.

As for pipes/hoppers, I'm not sure why that wouldn't work - vanilla hoppers seem to work okay for me, although I haven't tested any of those mod's pipes. I will download those mods and see if I can get that fixed for the next release too.

Thanks again!

**Comment by MoonManModding** [comment]
Hi,

The latest release found [here](https://www.curseforge.com/minecraft/mc-mods/emerging-technology-hydroponics/files/2854928) **removes** the Shredder automatic output to the Processor,  as I don't feel it will work well with the different types of plastic items.

I have tested vanilla hoppers on both machines and they appear to work fine. If you find this is still not the case, let me know! Also I have only had the opportunity to test the Thermal Series ducts with the machines, but these look like they work correctly too. 

If you still have problems, please add an image of your set up so I can attempt to replicate the issue.

Thanks 😅

**Comment by PlatinumFox** [comment]
Hello, I appreciate the speedy patch! Whatever you did worked I updated and all my pipes started working and the hoppers too. 
Thanks again!
