### ISSUE TITLE
unsure if this is on your end, but

### ISSUE THREAD

**Issue by Late-Night** [MoonManModding/EmergingTechnology#22]
if a grow lamp w/bulb is placed above a space that does not have a hydroponic bed in it, the game freezes

**Comment by MoonManModding** [comment]
Hi,

Thanks for letting me know! Unfortunately I'm having trouble replicating this - it seems to work fine for me. Would you mind running me through what exactly you were doing up to the game freeze (bulbs, removed the grow bed etc)?

Also, which version of the mod are you currently using?

Thanks again 👍

**Comment by Late-Night** [comment]
i said i was unsure
if you're not able to replicate it, it was my pc freezing for some reason

**Comment by MoonManModding** [comment]
Well it may still be a bug even if I'm not getting it 😉 I'll keep an eye on it and if someone else experiences it I will have another look.

Cheers
