### ISSUE TITLE
Discussion - Balance

### ISSUE THREAD

**Issue by MoonManModding** [MoonManModding/EmergingTechnology#23]
Hello all,

Thanks for your feedback, suggestions and bug reports so far 😎

I'm now looking into adjusting the balance for the mod, specifically in regards to energy capacity/usage, processor timings and recipes etc.

If you've played the mod a little and thought to yourself 'that seems overpowered' or 'this is too slow', let me know here!

**Comment by jena-th** [comment]
Oh, you're on a tough subject here, some people will argue and some others will argue in the other direction. My 2cts: make everything configurable, and let them sort this out by themselves…
I'm talking by the experience I had during the glorious introduction of the Immersive Engineering Garden Cloche… People whining about its OP-ess and people whining about the fact that you have to power it, and provide water to grow the crops balancing it in a way… Finally Blu send them all having fun with themselves and put a conf with a "decent" default… Which I ALWAYS multiply the efficiency by 3 like it was before the "balancing"…

**Comment by jena-th** [comment]
And, sorry if I look like I only talk about the hydroponics, but I meant it like a general rule: remove all the magic numbers, all the constants and turn them into config options with a "decent default"

**Comment by MoonManModding** [comment]
Yeah I totally agree. I've tried to make everything totally configurable for maximum flexibility, but I just wanted to make sure players who don't want to think about configuration can jump straight in without the mod feeling OP/weak - the decent default like you say. I don't feel I've played enough mods to get a sense for where that baseline difficulty is 😋

I think I may just eyeball it and do a default configuration that makes sense to me in that case. The only things hardcoded now are machine capacities (energy/fluid etc) which I'll probably just set to high-ish numbers.

Thanks for the input btw, much appreciated 😉

**Comment by jena-th** [comment]
I'm so hyped by your mod, it's natural that I do what I can to help ! :)
BTW, I'll try to stay up to date concerning the translation :)

**Comment by Tape-Dispenser** [comment]
with IRL hydroponics systems, often what can happen is that you will have to replace the medium. Maybe add a random chance for each media for it to be destroyed, making you have to replace it.

Then maybe for automation, have a new medium that has a more complicated recipie but has a very low/0 chance of being destroyed

**Comment by PlatinumFox** [comment]
i like the idea of creating a media that has a 0 chance to get destroyed

**Comment by MoonManModding** [comment]
> Maybe add a random chance for each media for it to be destroyed, making you have to replace it.

I had thought about adding this in a while ago, but worried it would get annoying with lots of Grow Beds. Think I'll add it in as a config option 😁

**Comment by MoonManModding** [comment]
Closing as the ideas have been implemented. If you think of more, just add a new issue. Thanks again all  🥰
