### ISSUE TITLE
Biomass generator. Process interruption bug.

### ISSUE THREAD

**Issue by genom10** [MoonManModding/EmergingTechnology#24]
Biomass consumed only at the finish of processing, but generation is on all the time. If you take biomass before processing finish, the energy stays.

**Comment by MoonManModding** [comment]
Hi,

Thanks for reporting this. Silly oversight on my part, I will put out a patch today to fix it 🤡

**Comment by MoonManModding** [comment]
Should be fixed in version 1.2.17-beta. Let me know if you have any more issues. Thanks again!
