### ISSUE TITLE
Synthetic meat issues

### ISSUE THREAD

**Issue by Tape-Dispenser** [MoonManModding/EmergingTechnology#25]
In ore dictionary, there's an issue with the meat. Synthetic meat is under rawMeat whereas recipies that require meat need, for example, listAllbeefraw. [example](https://imgur.com/a/Shyc1fi)

**Comment by MoonManModding** [comment]
Hi,

Thanks for reporting this. I have been trying to get the meats into the correct OreDict categories to work with all mods but obviously there's still work to do 😅

Below is a full list of the synthetic items and the matching OreDicts so far - would you mind letting me know which ones are incorrect?

**Raw Synthetic Chicken Meat**
- listAllchickenraw
- listAllmeatraw
- rawMeat

**Raw Synthetic Cow Meat**
- listAllbeefraw
- listAllmeatraw
- rawMeat

**Raw Synthetic Pig Meat**
- listAllporkraw
- listAllmeatraw
- rawMeat

**Cooked Synthetic Chicken Meat**
- listAllmeat
- listAllchickencooked
- listAllmeatcooked
- cookedMeat

**Cooked Synthetic Cow Meat**
- listAllmeat
- listAllbeefcooked
- listAllmeatcooked
- cookedMeat

**Cooked Synthetic Pig Meat**
- listAllmeat
- listAllporkcooked
- listAllmeatcooked
- cookedMeat

**Comment by Tape-Dispenser** [comment]
from what I can see that looks right, I'll have to make sure I have the most recent version

**Comment by Tape-Dispenser** [comment]
sorry, it's all good now, must have missed the new update

**Comment by MoonManModding** [comment]
Ah phew, thanks for reporting it though 😁 Keeps me on my toes!
