### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Tape-Dispenser** [MoonManModding/EmergingTechnology#26]
Hey, so I've been doing some research into hyroponics and how everything is made, and I was thinking I may be able to help with designing a pH system, along with nutrients. I'm not that great with coding, but I have some general knowledge and I've been trying to make this as an addon mod.

**Comment by MoonManModding** [comment]
Hi,

This sounds very interesting! I've been considering how I'd implement a pH/nutrient system but haven't settled on anything yet.

Could you give me some more details on how you think it should work and I can see if it's feasible for me to do?

Thanks 😁

**Comment by Tape-Dispenser** [comment]
I was either thinking you could have water at a base, say 7.0 pH, then use NBT data for the pH, so as not to add too many new blocks. I was thinking then adding nutrient-rich water, which also using NBT data would determine the N-P-K and micronutrient count, along with the pH NBT data

You'd have to add a fair bit of ores, along with a machine or two for all the nutrients, the mod I was making heavily depended on NuclearCraft for a lot of the chemicals, but I still had to add a lot of phosphate-based items. In the file attached I have what I was going to add in my expansion mod, near the bottom you can see what was needed for pH substances along with nutrients
[Add Ons.txt](https://github.com/MoonManModding/EmergingTechnology/files/4048616/Add.Ons.txt)

**Comment by MoonManModding** [comment]
Damn, if you had all that in an expansion mod it would be 10 times better than my mod 🤣

I had planned to add Vermiculite, perlite, rockwool etc at a later date so those shouldn't be a problem. I'm not very keen on the idea of depending on other mods for things outside of water/power etc though, so instead I may just put together a nice API to make it easier to create addons (Alchemistry would be great for this too). Same with ore generation too actually - I'd like to keep it as vanilla and lightweight as possible.

In terms of NPK, would there be unlimited combinations of N-P-K-pH for fluids? How would each element & pH affect growth?

**Comment by MoonManModding** [comment]
I've added these ideas into some documentation I will attempt to implement at a later date. Thank you again for your suggestions and well-thought-out ideas!

I will be sure to credit you when I get round to adding them 😊
