### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by PlatinumFox** [MoonManModding/EmergingTechnology#27]
Better way to automate/dispose seeds in harvesters. The seeds fill up very fast and spout everywhere. even something as simple as deleting excess seeds from spawning once the harvester reaches a fiull stack would be nice.

**Comment by MoonManModding** [comment]
Hi,

Thanks for bringing it up! This was something I'd planned to do, but guess it got lost in the pile.

I think my plan was to have ~4 output slots + 1 seed input slot, with the seed input autofilling. When the seed slot is full, excess seeds go into the 4 output slots (where they can be automated out). If everything is full I think the Harvester would just shut down.

How does that sound? 😁

**Comment by MoonManModding** [comment]
This should be implemented as of 1.2.18-beta. Thanks again for making the bug report/suggestion, it's very helpful indeed 😍
