### ISSUE TITLE
Crafting Logic

### ISSUE THREAD

**Issue by PlatinumFox** [MoonManModding/EmergingTechnology#28]
I think I have found an error in a crafting logic process.

-the auto filler needs plastic in order to craft it
      -the processor makes plastic
           -the processor needs water to do its job
                -using just emerging tech alone, i couldn't find or think of a way to create plastic as there 
                  is no other way to put water in the processor other than putting the filler next to it. 

the use of other mods is completely necessary in order to make plastic as far as i can tell.

**Comment by Tape-Dispenser** [comment]
to start, you need to create a machine case with nether quartz

**Comment by PlatinumFox** [comment]
yeah i know thats not the issue though. you need 2 plastic rods to craft the autofiller

**Comment by MoonManModding** [comment]
Hadn't even considered this 🥴 I will change the Water Filler recipe in the next release. Cheers!

**Comment by MoonManModding** [comment]
This should be fixed as of version 1.2.18-beta. Thank you again for reporting it, and please let me know if you have further issues :)
