### ISSUE TITLE
Texture Update

### ISSUE THREAD

**Issue by Dr-Mic** [MoonManModding/EmergingTechnology#31]
I was wondering if you had any plans to rework the textures for shredded plant/plastic/starch plus plastic waste and Biomass. They feel more like place holders and somewhat unfinished.

**Comment by MoonManModding** [comment]
Heh yes they are a little programmer-arty aren't they?

I wanted to add a couple more items then my plan was to ask around for an artist to redo the item textures. If you know of anyone, or any artists see this, let me know though 😊

**Comment by MoonManModding** [comment]
Found an artist. Decent textures are on their way!

Thanks for the feedback, keep it coming 👍
