### ISSUE TITLE
Dupe bug with harvester

### ISSUE THREAD

**Issue by Dr-Mic** [MoonManModding/EmergingTechnology#32]
When using a harvester to collect sugar cane, it breaks it and collects it when its more than one tall. However once it collects it it also drops it in the world. So if a sugar cane grows to two tall; its broken, the harvester has two, and it drops one in the world meaning you got three. From there you can just place it on top of one and get two every time.

PS. I seen the new textures, I like them.

**Comment by MoonManModding** [comment]
Hi,

Thanks for reporting this. Totally slipped my mind to test sugar cane with the new changes to the Harvester. I will fix this for the next release 👍

**Comment by MoonManModding** [comment]
This should be fixed in version 1.2.21-beta.

If you have any further issues with it, let me know.
