### ISSUE TITLE
Tissue Bioreactor wrong recipe

### ISSUE THREAD

**Issue by DevTimur** [MoonManModding/EmergingTechnology#33]
Tissue Bioreactor turn Samples into Syringes.
I think it should be opposite.

**Comment by MoonManModding** [comment]
Good to see you again!

Thanks for letting me know, I'll get it fixed for the next release.

**Comment by MoonManModding** [comment]
This should be fixed in version 1.2.21-beta.

If you have any further issues with it, let me know.
