### ISSUE TITLE
[Suggestion] Harvester power share

### ISSUE THREAD

**Issue by DevTimur** [MoonManModding/EmergingTechnology#34]
As it says, Harvester should share power to other harvesters in line, because cabling looks not as good.
![image](https://user-images.githubusercontent.com/22171136/72433025-2ba94f80-37a1-11ea-99d1-8ecaf04c2cae.png)

**Comment by DevTimur** [comment]
btw, harversters looks quite legit :-)

**Comment by MoonManModding** [comment]
Yeah the cable thing bothered me too - I was going to change the model so it had a port in the back but your idea is probably better 😁

I will put this in the next release, thanks!

**Comment by DevTimur** [comment]
You still can change model a bit, add small connection port like you did in lamps, that explains itself.

**Comment by MoonManModding** [comment]
This has been implemented in version 1.2.21-beta.

If you have any issues with it, let me know.
