### ISSUE TITLE
[BUG] Harvester pland seeds in bed without medium

### ISSUE THREAD

**Issue by DevTimur** [MoonManModding/EmergingTechnology#35]
As title says, Harvester pland seeds in bed without medium. Seeds pop out after tick.

**Comment by MoonManModding** [comment]
Hi,

Do you mean without water? Seeds should still grow fine without a growth medium. 

Thanks!

**Comment by MoonManModding** [comment]
This should be fixed in version 1.2.21-beta.

If you have any further issues with it, let me know.
