### ISSUE TITLE
[Feature Request] Harvester turn to nearby crop

### ISSUE THREAD

**Issue by DevTimur** [MoonManModding/EmergingTechnology#36]
![image](https://user-images.githubusercontent.com/22171136/72433525-2b5d8400-37a2-11ea-8a2d-5b5a58954a53.png)

Is it possible to make so Harvester turn and harvest nearby crops, not only one in front?
Just curious, it may hurt ballance a bit, so don't do it if not necessary.

**Comment by MoonManModding** [comment]
Yes definitely - I wanted to do this from the beginning but my animation skills were not good enough.

I think I could probably do this now, although I may not add it if it causes too much lag. Should be fine though and would be an awesome feature to have.

Thanks again 😁

**Comment by DevTimur** [comment]
No additional animation needed, m8. Just turn whole block into direction of fully grown crop, and play original animation.

Also, harvester harvest crops very fast, what timer does it got? Every tick, or per block updates? I think you should make this tile entity more relaxed, make so it check surrounding blocks every like 20-40 ticks (1-2 seccond), or even more. Considering how slow crops grow it shouldn't be a problem.

**Comment by MoonManModding** [comment]
Hi,

This feature should now be available in [version 1.3.8-beta](https://www.curseforge.com/minecraft/mc-mods/emerging-technology-hydroponics/files/2887898). 

Thanks again for the suggestion. Keep 'em coming! 😁
