### ISSUE TITLE
[BUG] Wierd Solar Panel

### ISSUE THREAD

**Issue by DevTimur** [MoonManModding/EmergingTechnology#37]
[PICTURE](https://i.gyazo.com/e1ee1a783d94db3f83695965671cdd57.gif)
As you can see in GIF, when i place new Solar Panel on battery, it generate 100 RF per cycle.
But if i place battery on already pre-charged Solar it generate 5000 RF per cycle.

I think something wrong here.

**Comment by MoonManModding** [comment]
This should be fixed in version 1.2.21-beta.

If you have any further issues with it, let me know.
