### ISSUE TITLE
[Feature Request] Wind Power

### ISSUE THREAD

**Issue by Late-Night** [MoonManModding/EmergingTechnology#39]
pretty self-explanatory
a block that generates more rf the higher it is

**Comment by MoonManModding** [comment]
Hi,

Thanks for the suggestion 😊 

As with the solar panel it's something I wanted to add but hesitated as it's been implemented in other mods really well. However, since I put in the solar panel anyway it would be silly not to have a wind turbine, so I'll try to sneak it into the next release 👍

**Comment by MoonManModding** [comment]
This has been implemented as of version 1.3.1-beta. 

Thanks again!
