### ISSUE TITLE
Can not find it

### ISSUE THREAD

**Issue by LoloElSupremo** [MoonManModding/EmergingTechnology#4]
Hello,
I do not see it in JEI or the craft.
Can it come from the fact that I have another mod?

**Comment by MoonManModding** [comment]
Which version of Minecraft/JEI are you using?

Are you searching for 'hydroponic' in JEI?

**Comment by LoloElSupremo** [comment]
1.12.2 I can not find it

**Comment by MoonManModding** [comment]
Could you please attach a screenshot of your search using JEI and the vanilla creative crafting menus?

Thanks

**Comment by LoloElSupremo** [comment]
https://imgur.com/a/tSgJ5OZ
:/

**Comment by MoonManModding** [comment]
Very strange. I can only assume the mod hasn't loaded. Is there an **Emerging Technology** tab in your creative menu?

Which .jar file did you place in your mods folder?

Thanks

**Comment by Digimasterhir0** [comment]
Oh, just use @hydroponics and JEI will show it.

**Comment by MoonManModding** [comment]
> Oh, just use @hydroponics and JEI will show it.

Think this may be the solution for now. Closing this issue but just stick a new one in if you still have problems.
