### ISSUE TITLE
Opening Harvester Inventory crashes game

### ISSUE THREAD

**Issue by DarkCoder28** [MoonManModding/EmergingTechnology#43]
In version 1.3.3, when I right click on the harvester, the game crashes with a description of "Ticking Player". I have attached my crash log. 
[crash-2020-01-19_13.34.57-server.txt](https://github.com/MoonManModding/EmergingTechnology/files/4083189/crash-2020-01-19_13.34.57-server.txt)

**Comment by MoonManModding** [comment]
Hi,

Did you have an earlier version of the mod installed prior to using 1.3.3? You may need to break and replace the Harvester to prevent this.

Please let me know if this does not work.

Thanks!
