### ISSUE TITLE
Agricraft crop issues

### ISSUE THREAD

**Issue by Deiwos** [MoonManModding/EmergingTechnology#44]
Version: 1.3.3

Hello. So, first of all, the json provided in the guide to set up the grow bed as an Agricraft soil doesn't work properly? The only way I was able to use the grow bed as a 'soil' was to set "ignoreMeta" to true, otherwise I wasn't able to place crop sticks on one at all no matter what I tried.
But, once I got that figured out I found out a more serious issue, which is the fact that the harvesters are both unable to plant on the crop sticks or harvest from them. This is using ones I've just placed in a test world now.

![2020-01-20_06 15 50](https://user-images.githubusercontent.com/13326231/72687856-c1503080-3b4d-11ea-8758-37431d5d04da.png)

**Comment by MoonManModding** [comment]
Hi,

Cheers for letting me know 👍 

I must have forgotton to update the wiki after changing the grow bed, so apologies for that. As you have discovered just adding the block with ignoreMeta should be fine now.

As for the Harvester, I actually haven't had a chance to test it out on Agricraft cropsticks yet. I'm not sure what is involved with getting them to play nicely but I will look into it and try to fix it for the next release.

Thanks again

**Comment by MoonManModding** [comment]
Hi,

I've looked into this and implemented the auto-harvest of crops grown on cropsticks, but it would take a bit more work to plant crops. 

My understanding of Agricraft however is that replanting seeds is unnecessary, as the player just right-clicks the crop to harvest which doesn't break the block - is this correct?

Cheers 👍

**Comment by Deiwos** [comment]
That's correct. The crop doesn't need to be broken by the harvester in the case of crop sticks.

**Comment by MoonManModding** [comment]
Alright, so in that case the Harvester will now emulate a right-click when dealing with an Agricraft cropsticks crop that is fully grown and will not attempt to plant any seeds on the crop sticks. How does that sound in terms of functionality?

**Comment by Deiwos** [comment]
That sounds perfect!

**Comment by MoonManModding** [comment]
Hi,

I've added this into [version 1.3.4-beta](https://www.curseforge.com/minecraft/mc-mods/emerging-technology-hydroponics/files/2865078) but have only performed cursory testing. Would you mind taking a look when you get the chance and letting me know if there are any issues?

Thanks again for the bug report 😁
