### ISSUE TITLE
Crash upon launching profile

### ISSUE THREAD

**Issue by PlatinumFox** [MoonManModding/EmergingTechnology#47]
didnt even make it to the title screen

[crash-2020-01-24_22.30.15-client.txt](https://github.com/MoonManModding/EmergingTechnology/files/4111595/crash-2020-01-24_22.30.15-client.txt)

**Comment by MoonManModding** [comment]
Hi,
Thanks for reporting this. Not sure why that didn't pop up in my testing. Looks like if you're using the latest beta you'll need Crafttweaker installed for now. Will fix this in the next release.

Thanks again

**Comment by Tape-Dispenser** [comment]
I believe that's a bug in the beta version of the mod, I had it as well

**Comment by MoonManModding** [comment]
Hi,

This should be resolved in the latest 1.3.5-beta release. If you still have issues let me know.

Thanks 😁
