### ISSUE TITLE
Rotating harvester facing up or down causes crash

### ISSUE THREAD

**Issue by swoolcock** [MoonManModding/EmergingTechnology#48]
Steps to reproduce:
1) Place a harvester
2) Use a yeta wrench (or similar) to point the harvester up or down
3) Give it power
4) Crash occurs.

First noticed in multiplayer (causes a server crash loop), managed to reproduce it every time in single player.

Running XXL Pants Pack 1.0.9: https://www.curseforge.com/minecraft/modpacks/xxl-pants-pack

https://paste.dimdev.org/vajuvozoqa.mccrash

**Comment by MoonManModding** [comment]
Damn, hadn't considered people rotating machines with tools. Thanks for the fix, will put out a new version when I get the chance 😁
