### ISSUE TITLE
Question - How to plant seeds?

### ISSUE THREAD

**Issue by Digimasterhir0** [MoonManModding/EmergingTechnology#5]
Hi! How can i plant some seeds and sugarcane? RMB did not work. May be it is an issue?
![2019-12-05_16 59 31](https://user-images.githubusercontent.com/47353693/70241764-a2a20000-1780-11ea-9029-66ca756cacfd.png)

Have a great day!
DigimasterHiro

**Comment by MoonManModding** [comment]
Looks like you'll need to raise the Grow Lights one block higher - they're occupying the space where the crop should go.

Let me know if it still doesn't work :)

**Comment by Digimasterhir0** [comment]
Fixed. Thank you!
