### ISSUE TITLE
Meat Discussion

### ISSUE THREAD

**Issue by PlatinumFox** [MoonManModding/EmergingTechnology#50]
just something I wanted to discuss
(Ive been using this in survival so this is based on that experience)

automation process for synth meat in my head is as follows
make plastic
get harvester for plants
make more plastic
make bio machines
use plastic for synth meat
synth meat not better than veggies

i went through the process of thinking how to automate the process of having harvesters use excess veggies to make plastic and then those resources get put into bio machines for scaffolding to make synth meat

synth meat is not any better than a carrot therefore in my head going after the synth meats is completely useless if players can just farm carrots or potatoes from harvesters. There is still wiggle room in the hunger shanks/bars to make the synth steak better than stuff like carrots but still worse than real meat.

**Comment by MoonManModding** [comment]
Hi,

Thanks for pointing this out 😁 Which values would you recommend for each cooked meat in this case? 

I've noticed that I also omitted a heal value from the custom tissue items so I will add that in too. 👍

**Comment by PlatinumFox** [comment]
From a player perspective i think they should be abov the veggies and below vanilla meats, just o players have an actual reason to obtain and farm them. I am not currently home but i will get back with later tonight.

**Comment by PlatinumFox** [comment]
From a player perspective i think they should be abov the veggies and below vanilla meats, just o players have an actual reason to obtain and farm them. I am not currently home but i will get back with later tonight.

**Comment by PlatinumFox** [comment]
Maybe around the same as a baked potato? Not sure what the healing range is but maybe it could be ever so slightly higher than a baked potatoes healing but lower than regular meat? Not sure how that works tho. Just an idea.

**Comment by MoonManModding** [comment]
Sounds good to me 😊 I've changed the synthetic meats restore 3 - 3.5 which I think is probably fair. I have also changed the hunger saturation to be a bit more forgiving.

**Comment by Tape-Dispenser** [comment]
Are the hunger and saturation values able to be changed in config?

**Comment by MoonManModding** [comment]
Not currently but I will attempt to add it for the next release 👍

**Comment by MoonManModding** [comment]
Hi,

This should now be available in the latest 1.3.5-beta release. The defaults have been bumped up and you can now edit the values using the config file. Any issues let me know 😁

Thanks all!
