### ISSUE TITLE
Amount of starch it takes to convert to bioplastic is too expensive

### ISSUE THREAD

**Issue by Acgamble** [MoonManModding/EmergingTechnology#51]
I was trying to get shredded starch to convert my starch into a block of bioplastic but the cost to convert is 9 so I was wondering if in future plans you can make it where potatoes or any other starch's when shredding them you get 4 shredded starch instead of 1 anyways just a suggestion hope you have a good day I would love to see this as a feature in the mod

**Comment by MoonManModding** [comment]
Hi,
Thanks for the suggestion 😁

I completely agree. I was thinking of dropping the total starch to create a block of bioplastic to 4 and the same for shredder plants, as with the shredded plastic. I will stick this in the next release.

Thanks again

**Comment by Acgamble** [comment]
Thanks for the update I'll be glad to see this in the future I love this mod so much and glad to see the mod improving so consistently

**Comment by MoonManModding** [comment]
Hi,

This should be available in the latest 1.3.5-beta release. Thanks again for the suggestion and the feedback 😍 Let me know if you have any further issues.
