### ISSUE TITLE
Empty Tissue Syringe translation

### ISSUE THREAD

**Issue by Smollet777** [MoonManModding/EmergingTechnology#52]
I suggest you to check code for syringe.
![image](https://user-images.githubusercontent.com/41921653/73589486-e054a800-44e7-11ea-9849-b862b8adb246.png)
Translation in lang file exists but not applying 
https://github.com/MoonManModding/EmergingTechnology/blob/8a940886d31566e270ede8732e30992862bb6eba/src/main/resources/assets/emergingtechnology/lang/ru_ru.lang#L45

**Comment by MoonManModding** [comment]
Thanks for that, will be fixed in the next release 😁
