### ISSUE TITLE
[Feature Request] Crafttweaker Support

### ISSUE THREAD

**Issue by Silverrain2004** [MoonManModding/EmergingTechnology#56]
As per title, I would like to request the addition of compatibility with Crafttweaker. As for Modpack-Maker this give us more possibility to tweak Recipes, Machine-Output and other Things for the need of every Modpack in customisation.

https://www.curseforge.com/minecraft/mc-mods/crafttweaker

For Craftweaker API:

https://docs.blamejared.com/1.12/en/#Dev_Area/Ingredients/

**Comment by MoonManModding** [comment]
Hi,

Thanks for the request - CraftTweaker support is something I'm working on, but as I'm not too familiar with it it's pretty untested.

The [latest beta version](https://www.curseforge.com/minecraft/mc-mods/emerging-technology-hydroponics/files/2872352) notionally has CraftTweaker support, although I've heard it only partially works/doesn't work at all.

If you or anyone else is willing to test it out and report back (ideally attached with the CraftTweaker file used) that would be amazing and save me a lot of getting it wrong 🤩 

Thanks again!

**Comment by MoonManModding** [comment]
Hi,

I believe I have fixed the existing bugs with CraftTweaker support in the latest [version 1.3.7-beta](https://www.curseforge.com/minecraft/mc-mods/emerging-technology-hydroponics/files/2882540). It should now work as intended.

If there are any issues with it or improvements you think should be added, please let me know in a new issue. Thanks 😁
