### ISSUE TITLE
Feature request - IC2 Support

### ISSUE THREAD

**Issue by jamesjimmy88** [MoonManModding/EmergingTechnology#6]
As per title, I would like to request the addition of compatibility with IC2's crops (for the Grow Beds) and power system (for the Grow Lights).

**Comment by MoonManModding** [comment]
It's something I'm looking into, although I'm not having much luck finding up to date documentation on IC2. I will definitely add IC2 support eventually, but for now you'll need to convert EU to RF for the lights and stick to vanilla/other mod's crops. Sorry about that!

**Comment by captcookie** [comment]
there's a ic2 addon that you can use that works fine. https://www.curseforge.com/minecraft/mc-mods/tatw

**Comment by MoonManModding** [comment]
Sticking this on the backburner for now - I think I will focus on just implementing the crops when I get round to it. Cheers!
