### ISSUE TITLE
[Suggestion] Solar Panels share power

### ISSUE THREAD

**Issue by DevTimur** [MoonManModding/EmergingTechnology#67]
Maybe it would be reasonable if Solar Panels share power. So I can make big solar field, and get all the power from one spot.
Maybe make so ALL power sharing machines was one big multiblock machine, or maybe make so they all share power in one direction. Anyways it looks better when all machines placed in lines.

**Comment by MoonManModding** [comment]
Hi,

Great suggestion 😁

I've implemented this so generators push energy 'through' other generators until it hits a machine that consumes energy. It won't be able to go around corners but I don't think that would be necessary anyway.

Thanks!

**Comment by MoonManModding** [comment]
This feature should be available as of [version 1.3.9-beta](https://www.curseforge.com/minecraft/mc-mods/emerging-technology-hydroponics/files/2889339)

Please let me know if you have any issues with it. Thanks!
