### ISSUE TITLE
[Suggestion] Crafttweaker support

### ISSUE THREAD

**Issue by noeneto** [MoonManModding/EmergingTechnology#68]
The mod is amazing and could be even more with a crafttweaker support! :D

**Comment by MoonManModding** [comment]
Hi,

Thanks for the suggestion! In theory it already has CraftTweaker support 😁

I have done some basic testing of CraftTweaker and it seems to work. For example:

```
import mods.emergingtechnology.Processor;

Processor.addRecipe(<minecraft:diamond>, <minecraft:redstone>);
```

Please let me know if you need more information or something doesn't work.

Thanks!
