### ISSUE TITLE
[Suggestion] Config option to remove biome requirement for Waste Collector

### ISSUE THREAD

**Issue by ghost** [MoonManModding/EmergingTechnology#69]
I would love to use the Waste Collector in a skyblock-esque pack I am working on, but in my world there are no ocean/river/beach biomes, so I was hoping that there could be a simple config option to disable this requirement for machine operation so that this machine can be used in a wider range of packs.

**Comment by MoonManModding** [comment]
Hi,

Cheers for the suggestion! Happy to hear you're interested in using it in your modpack 😊

I had meant to add this option for the Collector and Tidal generator a while ago but it must have gotten lost in the pile. It will be available in the next release.

Thanks again

**Comment by MoonManModding** [comment]
This feature should be available as of [version 1.3.9-beta](https://www.curseforge.com/minecraft/mc-mods/emerging-technology-hydroponics/files/2889339)

Please let me know if you have any issues with it. Thanks!
