### ISSUE TITLE
Harvester Crash

### ISSUE THREAD

**Issue by ghost** [MoonManModding/EmergingTechnology#73]
One of my testers provided me with this crash log caused by the harvester

Forge: 1.12.2 - 14.23.5.2847
Mod: 1.12.2-1.3.9-beta

[log](https://pastebin.com/4WVJDRxJ)

Edit: I see 2 updates were released since beta 9 in the last 24 hours. You can go ahead and close this issue if you think it was specifically fixed in one of those updates.

**Comment by MoonManModding** [comment]
Hi,

Thanks for reporting this. Definitely an oversight on my part and hasn't been fixed in subsequent updates. I will try to get this resolved ASAP!

**Comment by MoonManModding** [comment]
Hi,

In theory this should be resolved in [1.3.12-alpha](https://www.curseforge.com/minecraft/mc-mods/emerging-technology-hydroponics/files/2892110) although I haven't had a chance to test it myself yet.

Would you mind asking your tester to use this version and see if the issue persists?

Thanks 😁
