### ISSUE TITLE
[Suggestion] Carbon dioxide compatibility

### ISSUE THREAD

**Issue by GSValore** [MoonManModding/EmergingTechnology#75]
## Suggestion

The Diffuser machine accept carbon dioxide, but NuclearCraft calls it "carbon_dioxide" instead for theirs.  Maybe supporting that directly or providing a config option list of accepted liquid names for use as an alternative.

**Comment by MoonManModding** [comment]
Hi,

Thanks for pointing this out, I'd thought the Nuclearcraft carbon dioxide worked already (doh). I've added "carbon_dioxide" as valid for now, and when I get around to overhauling the recipe system I will provide the option to add custom fluids properly to recipes.

**Comment by MoonManModding** [comment]
This should be available from [version 1.3.13-beta](https://www.curseforge.com/minecraft/mc-mods/emerging-technology-hydroponics/files/2893142). Please let me know if you encounter any issues with it. Thanks again!
