### ISSUE TITLE
Please display the energy in either RF/t or RF/s

### ISSUE THREAD

**Issue by Gliese-832-c** [MoonManModding/EmergingTechnology#79]
Nowhere does it state what a cycle is and how long it lasts. No other mod uses "cycles". Please display the energy in commonly used units, like RF/t or RF/s, to allow for better compatiblity with other mods and a better user experience. It would also make modpack development easier because it would allow the devs to see how much energy the generators produce and balance them.

**Comment by MoonManModding** [comment]
Yeah the cycle thing is a bit half-baked, I'll sort this for the next release. Cheers 👍

**Comment by MoonManModding** [comment]
Hi,

This should be done in [version 1.3.17-beta](https://www.curseforge.com/minecraft/mc-mods/emerging-technology-hydroponics/files/2897379). Any problems please let me know.

Thanks again!
