### ISSUE TITLE
Feature Request: Automation

### ISSUE THREAD

**Issue by LatentDesire** [MoonManModding/EmergingTechnology#8]
I may be dumb, but is there a way to automate the extraction of the grown crops? I can't seem to figure it out. If it's not already I thing, I'd like to request it.

**Comment by MoonManModding** [comment]
Thanks for the suggestion :) To be honest it's not something I had intended to add, as other mods provide this functionality far better than I could implement. 

I am however looking into reading the current growth status of a crop on a grow bed so it can be passed via redstone/OpenComputers to the auto-farmers from other mods.
