### ISSUE TITLE
The Solar Panel hitbox should be like the stair hitbox.

### ISSUE THREAD

**Issue by Gliese-832-c** [MoonManModding/EmergingTechnology#80]
Please make it so that the solar panels hitbox is like a stair hitbox, so you can walk on it without having to jump.

**Comment by MoonManModding** [comment]
Hi,

This should be available in [version 1.3.17-beta](https://www.curseforge.com/minecraft/mc-mods/emerging-technology-hydroponics/files/2897379) onwards. I have also adjusted the hitboxes for the Wind Generator, Harvester and Solar Cooker. Please let me know if there any issues.

Thanks!
