### ISSUE TITLE
[Suggestion] More Galacticraft Compatibility.

### ISSUE THREAD

**Issue by Rick-Al** [MoonManModding/EmergingTechnology#89]
During some testing I discovered that Blocks of Clear Bioplastic and Solar Glass do not count as seal-able blocks when used with Galacticraft's Oxygen Sealer. It will view the room as "Area too big, or unsealed"

**Comment by MoonManModding** [comment]
Hi,

Galacticraft actually has a method of adding blocks from other mods to the sealable block list. There is a guide located [here](https://wiki.micdoodle8.com/wiki/SealableIDs#Galacticraft_3) which should walk you through it.

If you have any issues with this please let me know.

Thanks!
