### ISSUE TITLE
Guide Lights

### ISSUE THREAD

**Issue by PlatinumFox** [MoonManModding/EmergingTechnology#91]
Feature Request:
Guide light to be placeable on all sides of a block like an end rod.

(love the design/texture btw just downloaded latest beta today)

**Comment by MoonManModding** [comment]
Hi,

Thanks for the suggestion - I had planned to do this initially but ran out of time. I'll try to add it to the next release.

Cheers!

**Comment by MoonManModding** [comment]
This should be available in [version 1.3.23-alpha](https://www.curseforge.com/minecraft/mc-mods/emerging-technology-hydroponics/files/2920078) onwards. Please let me know if there are any issues, thanks again for the suggestion 😁
