### ISSUE TITLE
Harvesters only seem to work when you look directly at them.

### ISSUE THREAD

**Issue by RnChan408** [MoonManModding/EmergingTechnology#98]
I've come across this weird quirk where you have to look in the direction of a harvester for them to do anything, quite often you'll come back to unharvested crops that then get harvested and replanted after a little bit. 
I can even be right next to them but if I look away you don't hear any crops being harvested and look back at them shows fully grown crops that all get harvested at the same time which could mean they only work if they're rendered by the player.

**Comment by MoonManModding** [comment]
Hi,

Thanks for reporting this. This was an issue a while ago but I thought I'd resolved it. Can I assume you're using the latest release version?

Cheers 😁

**Comment by RnChan408** [comment]
Yeah, version 1.3.25.

**Comment by delprince979** [comment]
I know this doesn't really help, but I've also been having this issue, so it's not just Lucidcream who's experiencing it.

Using version 1.3.25, and if it matters at all, I've got liquid/energy/item pipes from both Thermal Dynamics and Cyclic linked up to them.

**Comment by delprince979** [comment]
Hi, I'm really sorry I don't mean to be a pest, but is there any news as to when/if this will be patched? It's throwing a wrench into some automation I had set up and I'm not sure whether I should wait for a fix or re-engineer what I had set up. Thank you in advance for any info you can give, I know you're probably really busy!

**Comment by MoonManModding** [comment]
> Hi, I'm really sorry I don't mean to be a pest, but is there any news as to when/if this will be patched? 

Apologies, as you say a very busy few months. I will work on getting this resolved this week 👍

**Comment by MoonManModding** [comment]
I believe this should be sorted in the [latest alpha](https://www.curseforge.com/minecraft/mc-mods/emerging-technology-hydroponics/files/2997589). If not, please let me know.

**Comment by delprince979** [comment]
It's working perfectly now, thank you so much! Sorry if I rushed you or anything, I knew you were probably busy and was just wondering. Thank you so much for the speedy reply/fix though, this helps out a lot!

**Comment by MoonManModding** [comment]
Phew! Not at all, it was on my list so just had to find time 😁

@Lucidcream if you're still having issues with this please give me a shout.
